import { useState } from 'react';
import { api } from '../services/api.js';

export function UserManagement({users,onChanged}) {
  const [editing,setEditing]=useState(); const [error,setError]=useState('');
  const save=async(event)=>{event.preventDefault();try{await api.patch(`/admin/users/${editing.id}`,{name:editing.name,email:editing.email,licenseNumber:editing.licenseNumber||undefined,phone:editing.phone||undefined});setEditing(null);onChanged();}catch(requestError){setError(requestError.response?.data?.message??'Could not update user.');}};
  const remove=async(user)=>{if(!window.confirm(`Remove ${user.name}? This also removes their driver assignment, if any.`))return;try{await api.delete(`/admin/users/${user.id}`);onChanged();}catch(requestError){setError(requestError.response?.data?.message??'Could not remove user.');}};
  return <section className="user-table"><div className="table-head"><div><p className="section-label">Access directory</p><h2>Users & roles</h2></div><span>{users.length} accounts</span></div>{error&&<p className="error">{error}</p>}{editing&&<form className="user-edit-form" onSubmit={save}><label>Name<input required value={editing.name} onChange={event=>setEditing({...editing,name:event.target.value})}/></label><label>Email<input required type="email" value={editing.email} onChange={event=>setEditing({...editing,email:event.target.value})}/></label>{editing.role==='DRIVER'&&<><label>Licence<input value={editing.licenseNumber} onChange={event=>setEditing({...editing,licenseNumber:event.target.value})}/></label><label>Phone<input value={editing.phone} onChange={event=>setEditing({...editing,phone:event.target.value})}/></label></>}<button>Save details</button><button type="button" className="text" onClick={()=>setEditing(null)}>Cancel</button></form>}{users.map(user=><article key={user.id} className="user-row"><span className="avatar">{user.name.slice(0,1)}</span><div><strong>{user.name}</strong><small>{user.email}</small>{user.license_number&&<small>Licence: {user.license_number}</small>}</div><span className={`role role-${user.role.toLowerCase()}`}>{user.role}</span><div className="user-actions"><button type="button" className="text" onClick={()=>setEditing({id:user.id,name:user.name,email:user.email,role:user.role,licenseNumber:user.license_number??'',phone:user.phone??''})}>Edit</button><button type="button" className="text danger-text" onClick={()=>remove(user)}>Remove</button></div></article>)}</section>;
}
