import { pool } from '../config/database.js'; import { redis } from '../config/redis.js'; import { distanceInMeters } from '../utils/geo.js'; import { HttpError } from '../utils/http-error.js';
export async function assignmentForDriver(userId) { return (await pool.query(`SELECT d.id driver_id,b.id bus_id,b.bus_number,b.status,r.id route_id,r.name route_name FROM drivers d JOIN bus_assignments a ON a.driver_id=d.id JOIN buses b ON b.id=a.bus_id LEFT JOIN routes r ON r.id=b.route_id WHERE d.user_id=$1`,[userId])).rows[0]; }
export async function routeStops(routeId) { return (await pool.query(`SELECT s.id,s.name,s.latitude::float,s.longitude::float,rs.stop_order FROM route_stops rs JOIN stops s ON s.id=rs.stop_id WHERE rs.route_id=$1 AND s.latitude IS NOT NULL AND s.longitude IS NOT NULL ORDER BY rs.stop_order`,[routeId])).rows; }
async function latest(busId) { try { const value=redis && await redis.get(`bus:${busId}:location`); if(value) return JSON.parse(value); } catch {} return (await pool.query(`SELECT latitude::float,longitude::float,speed_kph::float,recorded_at FROM location_history WHERE bus_id=$1 ORDER BY recorded_at DESC LIMIT 1`,[busId])).rows[0] ?? null; }
function progress(location,stops) { if(!location||!stops.length) return {currentStop:null,nextStop:stops[0]??null}; const index=stops.reduce((best,stop,i)=>distanceInMeters(location.latitude,location.longitude,stop.latitude,stop.longitude)<best.distance?{i,distance:distanceInMeters(location.latitude,location.longitude,stop.latitude,stop.longitude)}:best,{i:0,distance:Infinity}).i; return {currentStop:stops[index],nextStop:stops[index+1]??null}; }
export async function driverSnapshot(userId) { const assignment=await assignmentForDriver(userId); if(!assignment) throw new HttpError(404,'No bus is assigned to this driver.'); const stops=await routeStops(assignment.route_id); const location=await latest(assignment.bus_id); const active=(await pool.query('SELECT id,started_at FROM active_routes WHERE bus_id=$1 AND ended_at IS NULL',[assignment.bus_id])).rows[0]; return {assignment,activeRoute:active??null,location,...progress(location,stops)}; }
export async function startRoute(userId) { const assignment=await assignmentForDriver(userId); if(!assignment) throw new HttpError(404,'No bus is assigned to this driver.'); await pool.query(`INSERT INTO active_routes(bus_id,driver_id,route_id) VALUES($1,$2,$3) ON CONFLICT(bus_id) DO UPDATE SET driver_id=EXCLUDED.driver_id,route_id=EXCLUDED.route_id,started_at=NOW(),ended_at=NULL`,[assignment.bus_id,assignment.driver_id,assignment.route_id]); await pool.query(`UPDATE buses SET status='ACTIVE' WHERE id=$1`,[assignment.bus_id]); return driverSnapshot(userId); }
export async function endRoute(userId) { const assignment=await assignmentForDriver(userId); if(!assignment) throw new HttpError(404,'No bus is assigned to this driver.'); await pool.query('UPDATE active_routes SET ended_at=NOW() WHERE bus_id=$1 AND ended_at IS NULL',[assignment.bus_id]); await pool.query(`UPDATE buses SET status='INACTIVE' WHERE id=$1`,[assignment.bus_id]); return driverSnapshot(userId); }
export async function updateLocation(userId,{latitude,longitude,speedKph}) { const assignment=await assignmentForDriver(userId); if(!assignment) throw new HttpError(404,'No bus is assigned to this driver.'); const active=(await pool.query('SELECT id FROM active_routes WHERE bus_id=$1 AND ended_at IS NULL',[assignment.bus_id])).rowCount; if(!active) throw new HttpError(409,'Start your route before sending location.'); const location={latitude,longitude,speedKph:speedKph??null,recordedAt:new Date().toISOString()}; await pool.query('INSERT INTO location_history(bus_id,latitude,longitude,speed_kph) VALUES($1,$2,$3,$4)',[assignment.bus_id,latitude,longitude,speedKph??null]); try { if(redis) await redis.set(`bus:${assignment.bus_id}:location`,JSON.stringify(location),'EX',120); } catch {} return {busId:assignment.bus_id,location,...progress(location,await routeStops(assignment.route_id))}; }
export async function busesForStudents() { const buses=(await pool.query(`SELECT b.id,b.bus_number,b.status,r.name route_name,r.id route_id FROM buses b LEFT JOIN routes r ON r.id=b.route_id ORDER BY b.bus_number`)).rows; return Promise.all(buses.map(async(bus)=>{const location=bus.status==='ACTIVE'?await latest(bus.id):null; const stops=await routeStops(bus.route_id); return {...bus,location,...progress(location,stops)};})); }
export async function busDetails(id) { const bus=(await pool.query(`SELECT b.id,b.bus_number,b.status,r.name route_name,r.id route_id FROM buses b LEFT JOIN routes r ON r.id=b.route_id WHERE b.id=$1`,[id])).rows[0]; if(!bus) throw new HttpError(404,'Bus not found.'); const stops=await routeStops(bus.route_id); const location=await latest(bus.id); return {...bus,location,stops,...progress(location,stops)}; }
function indiaClock(date) { return new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(date); }
export async function busSchedule(id) {
  const now=new Date(); const today=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Kolkata',weekday:'short'}).format(now).toUpperCase(); const clock=indiaClock(now);
  const all=(await pool.query(`SELECT id,schedule_name,days_of_week,departure_time::text FROM bus_schedules WHERE bus_id=$1 AND is_active=true ORDER BY departure_time`,[id])).rows;
  if(!all.length)return null;
  let schedule=all.find(item=>item.days_of_week.includes(today)&&item.departure_time.slice(0,5)>=clock); let daysAhead=0; let serviceDay=today;
  if(!schedule) for(let offset=1;offset<=7&&!schedule;offset++) { const date=new Date(now.getTime()+offset*86400000); const day=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Kolkata',weekday:'short'}).format(date).toUpperCase(); const candidate=all.find(item=>item.days_of_week.includes(day)); if(candidate) { schedule=candidate; daysAhead=offset; serviceDay=day; } }
  if(!schedule)return null;
  const stops=(await pool.query(`SELECT s.name,s.latitude::float,s.longitude::float,sst.stop_order,sst.expected_arrival_time::text FROM schedule_stop_times sst JOIN stops s ON s.id=sst.stop_id WHERE sst.schedule_id=$1 ORDER BY sst.stop_order`,[schedule.id])).rows;
  const nextStop=daysAhead ? stops[0] : stops.find(stop=>stop.expected_arrival_time.slice(0,5)>=clock)??stops[0];
  return {...schedule,stops,nextStop,serviceDay,isNextServiceDay:daysAhead>0,daysAhead};
}
