import { useEffect, useState } from 'react';
import { api } from '../services/api.js';

const initial = { name: '', email: '', password: '', role: 'STUDENT', licenseNumber: '', phone: '' };
export function AdminDashboard() {
  const [users, setUsers] = useState([]); const [form, setForm] = useState(initial); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const load = () => api.get('/admin/users').then((response) => setUsers(response.data.data.users)).catch(() => setError('Unable to load users.'));
  useEffect(load, []);
  const submit = async (event) => { event.preventDefault(); setError(''); setMessage(''); try { await api.post('/admin/users', form); setForm(initial); setMessage('Account created successfully.'); load(); } catch (requestError) { setError(requestError.response?.data?.message ?? requestError.response?.data?.errors?.[0]?.message ?? 'Could not create account.'); } };
  return <section className="workspace"><div className="intro"><div><p className="eyebrow">System administration</p><h1>Manage campus access.</h1><p>Create students, drivers, and other administrators locally.</p></div><div className="time-card"><span>Total accounts</span><strong>{users.length}</strong><small>Role-based access enabled</small></div></div><div className="admin-grid"><form className="admin-form" onSubmit={submit}><p className="section-label">New account</p><h2>Add a user or driver</h2><label>Name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Email<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label>Temporary password<input required minLength="8" type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /></label><label>Role<select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option value="STUDENT">Student</option><option value="DRIVER">Driver</option><option value="ADMIN">System admin</option></select></label>{form.role === 'DRIVER' && <><label>Driver licence<input required value={form.licenseNumber} onChange={(event) => setForm({ ...form, licenseNumber: event.target.value })} /></label><label>Phone (optional)<input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label></>}{error && <p className="error">{error}</p>}{message && <p className="success">{message}</p>}<button>Create account</button></form><section className="user-table"><div className="table-head"><div><p className="section-label">Access directory</p><h2>Users & roles</h2></div><span>{users.filter((user) => user.role === 'DRIVER').length} drivers</span></div>{users.map((user) => <article key={user.id} className="user-row"><span className="avatar">{user.name.slice(0,1)}</span><div><strong>{user.name}</strong><small>{user.email}</small>{user.license_number && <small>Licence: {user.license_number}</small>}</div><span className={`role role-${user.role.toLowerCase()}`}>{user.role}</span></article>)}</section></div></section>;
}
