import { useEffect, useState } from 'react';
import { api } from '../services/api.js';
import { createSocket } from '../services/socket.js';
import { FleetMap } from '../components/FleetMap.jsx';
import { LiveMap } from '../components/LiveMap.jsx';
import { NotificationCenter } from '../components/NotificationCenter.jsx';
import { ScheduleManager } from '../components/ScheduleManager.jsx';
import { UserManagement } from '../components/UserManagement.jsx';

const initial={name:'',email:'',password:'',role:'STUDENT',licenseNumber:'',phone:'',busId:''};
export function AdminDashboard(){
  const [users,setUsers]=useState([]),[buses,setBuses]=useState([]),[trackingBuses,setTrackingBuses]=useState([]),[selected,setSelected]=useState('all'),[schedule,setSchedule]=useState(null),[form,setForm]=useState(initial),[message,setMessage]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  const loadTracking=()=>api.get('/tracking/buses').then(response=>setTrackingBuses(response.data.data.buses)).catch(()=>{});
  const load=async()=>{try{const [u,b,t]=await Promise.all([api.get('/admin/users'),api.get('/admin/buses'),api.get('/tracking/buses')]);setUsers(u.data.data.users);setBuses(b.data.data.buses);setTrackingBuses(t.data.data.buses);}catch(requestError){setError(requestError.response?.data?.message??'Admin API is unavailable.');}finally{setLoading(false);}};
  useEffect(()=>{const socket=createSocket();socket.on('bus:location',loadTracking);load();return()=>socket.disconnect();},[]);
  useEffect(()=>{if(selected==='all'){setSchedule(null);return;}api.get(`/tracking/buses/${selected}/schedule`).then(response=>setSchedule(response.data.data.schedule)).catch(()=>setSchedule(null));},[selected]);
  const submit=async(event)=>{event.preventDefault();setError('');try{await api.post('/admin/users',form);setForm(initial);setMessage('Account and driver/bus assignment created.');load();}catch(requestError){setError(requestError.response?.data?.message??requestError.response?.data?.errors?.[0]?.message??'Could not create account.');}};
  if(loading)return <section className="workspace"><h1>Loading administration…</h1></section>;
  const selectedBus=selected==='all'?null:trackingBuses.find(bus=>String(bus.id)===selected);
  return <section className="workspace"><div className="intro"><div><p className="eyebrow">System administration</p><h1>Manage campus transport.</h1><p>Monitor buses, communicate service changes, manage schedules, and control user access.</p></div><div className="time-card"><span>Total accounts</span><strong>{users.length}</strong><small>Role-based access enabled</small></div></div>{error&&<p className="error">{error}</p>}<NotificationCenter canSend/><section className="fleet-section"><div className="section-title"><div><p className="section-label">Fleet monitor</p><h2>Live bus locations</h2></div><label className="bus-picker">Show on map<select value={selected} onChange={event=>setSelected(event.target.value)}><option value="all">All active buses</option>{trackingBuses.map(bus=><option key={bus.id} value={bus.id}>{bus.bus_number} · {bus.status}</option>)}</select></label></div><FleetMap buses={trackingBuses} selectedBusId={selected}/>{selectedBus&&<div className="selected-bus-map"><p className="section-label">Selected bus detail</p><LiveMap key={`${selected}-${schedule?.id??'none'}`} bus={selectedBus} schedule={schedule}/></div>}</section><ScheduleManager buses={buses}/><section className="section-title"><div><p className="section-label">Account administration</p><h2>Add, edit, or remove users</h2></div></section><div className="admin-grid"><form className="admin-form" onSubmit={submit}><p className="section-label">Add user</p><h2>Create account</h2><label>Name<input required value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></label><label>Temporary password<input required minLength="8" type="password" value={form.password} onChange={event=>setForm({...form,password:event.target.value})}/></label><label>Role<select value={form.role} onChange={event=>setForm({...form,role:event.target.value,busId:''})}><option value="STUDENT">Student</option><option value="DRIVER">Driver</option><option value="ADMIN">System admin</option></select></label>{form.role==='DRIVER'&&<><label>Driver licence<input required value={form.licenseNumber} onChange={event=>setForm({...form,licenseNumber:event.target.value})}/></label><label>Bus number<select required value={form.busId} onChange={event=>setForm({...form,busId:event.target.value})}><option value="">Select required bus</option>{buses.map(bus=><option key={bus.id} value={bus.id}>{bus.bus_number}{bus.driver_name?` — reassign from ${bus.driver_name}`:''}</option>)}</select></label><label>Phone (optional)<input value={form.phone} onChange={event=>setForm({...form,phone:event.target.value})}/></label></>}{message&&<p className="success">{message}</p>}<button>Create account</button></form><UserManagement users={users} onChanged={load}/></div></section>;
}
