import { useEffect,useState } from 'react';
import { LiveMap } from '../components/LiveMap.jsx';
import { NotificationCenter } from '../components/NotificationCenter.jsx';
import { api } from '../services/api.js';
import { createSocket } from '../services/socket.js';

export function StudentDashboard(){
  const [buses,setBuses]=useState([]),[selected,setSelected]=useState(''),[schedule,setSchedule]=useState(null),[error,setError]=useState('');
  useEffect(()=>{const socket=createSocket();const loadBuses=()=>api.get('/tracking/buses').then(r=>{setBuses(r.data.data.buses);setSelected(current=>current||String(r.data.data.buses[0]?.id||''));r.data.data.buses.forEach(b=>socket.emit('bus:join',b.id));}).catch(e=>setError(e.response?.data?.message??'Unable to load buses'));socket.on('bus:location',loadBuses);loadBuses();const timer=setInterval(loadBuses,10000);return()=>{clearInterval(timer);socket.disconnect();};},[]);
  useEffect(()=>{if(selected)api.get(`/tracking/buses/${selected}/schedule`).then(r=>setSchedule(r.data.data.schedule)).catch(()=>setSchedule(null));},[selected]);
  const bus=buses.find(b=>String(b.id)===selected);
  return <section className="workspace"><div className="intro"><div><p className="eyebrow">IIT Ropar transport</p><h1>Your campus ride, in real time.</h1><p>Select a bus to show only its live location and timetable.</p></div><label className="bus-picker">Trace bus<select value={selected} onChange={e=>setSelected(e.target.value)}>{buses.map(b=><option key={b.id} value={b.id}>{b.bus_number}</option>)}</select></label></div>{error&&<p className="error">{error}</p>}<NotificationCenter/><div className="tracking-grid"><LiveMap key={`${selected}-${schedule?.id??'none'}`} bus={bus} schedule={schedule}/><aside className="arrival-card"><p className="section-label">{schedule?.isNextServiceDay?'Next service':'Today'} · {schedule?.serviceDay??'No service'}</p><h2>{schedule?.schedule_name??'No schedule yet'}</h2>{schedule?<><p>{schedule.isNextServiceDay?'Next departure':'Departs'} {schedule.departure_time?.slice(0,5)} · Next: <b>{schedule.nextStop?.name}</b> at <b>{schedule.nextStop?.expected_arrival_time?.slice(0,5)}</b></p>{schedule.isNextServiceDay&&<p className="arrival-time">Today’s buses have finished. Showing the first bus on the next service day.</p>}<div className="schedule-list">{schedule.stops.map(stop=><div className={stop.name===schedule.nextStop?.name&&stop.expected_arrival_time===schedule.nextStop?.expected_arrival_time?'active-schedule-stop':''} key={stop.stop_order}><span>{stop.stop_order}. {stop.name}</span><b>{stop.expected_arrival_time.slice(0,5)}</b></div>)}</div></>:<p>The administrator can add a timetable for this bus.</p>}</aside></div></section>;
}
